### ISSUE TITLE
Error loading pano.ckpt model

### ISSUE THREAD

**Issue by srttt** [Tangshitao/MVDiffusion#52]
python demo.py --text "This kitchen is a charming blend of rustic and modern, featuring a large reclaimed wood island with marble countertop, a sink surrounded by cabinets. To the left of the island, a stainless-steel refrigerator stands tall. To the right of the sink, built-in wooden cabinets painted in a muted."
/root/autodl-tmp/anaconda3/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
/root/autodl-tmp/code/MVDiffusion/demo.py:72: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('/root/autodl-tmp/files/pano.ckpt', map_location='cpu')['state_dict'], strict=True)
Traceback (most recent call last):
  File "/root/autodl-tmp/code/MVDiffusion/demo.py", line 72, in <module>
    model.load_state_dict(torch.load('/root/autodl-tmp/files/pano.ckpt', map_location='cpu')['state_dict'], strict=True)
  File "/root/autodl-tmp/anaconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PanoGenerator:
        Missing key(s) in state_dict: "vae.encoder.mid_block.attentions.0.to_q.weight", "vae.encoder.mid_block.attentions.0.to_q.bias", "vae.encoder.mid_block.attentions.0.to_k.weight", "vae.encoder.mid_block.attentions.0.to_k.bias", "vae.encoder.mid_block.attentions.0.to_v.weight", "vae.encoder.mid_block.attentions.0.to_v.bias", "vae.encoder.mid_block.attentions.0.to_out.0.weight", "vae.encoder.mid_block.attentions.0.to_out.0.bias", "vae.decoder.mid_block.attentions.0.to_q.weight", "vae.decoder.mid_block.attentions.0.to_q.bias", "vae.decoder.mid_block.attentions.0.to_k.weight", "vae.decoder.mid_block.attentions.0.to_k.bias", "vae.decoder.mid_block.attentions.0.to_v.weight", "vae.decoder.mid_block.attentions.0.to_v.bias", "vae.decoder.mid_block.attentions.0.to_out.0.weight", "vae.decoder.mid_block.attentions.0.to_out.0.bias". 
        Unexpected key(s) in state_dict: "text_encoder.text_model.embeddings.position_ids", "vae.encoder.mid_block.attentions.0.query.weight", "vae.encoder.mid_block.attentions.0.query.bias", "vae.encoder.mid_block.attentions.0.key.weight", "vae.encoder.mid_block.attentions.0.key.bias", "vae.encoder.mid_block.attentions.0.value.weight", "vae.encoder.mid_block.attentions.0.value.bias", "vae.encoder.mid_block.attentions.0.proj_attn.weight", "vae.encoder.mid_block.attentions.0.proj_attn.bias", "vae.decoder.mid_block.attentions.0.query.weight", "vae.decoder.mid_block.attentions.0.query.bias", "vae.decoder.mid_block.attentions.0.key.weight", "vae.decoder.mid_block.attentions.0.key.bias", "vae.decoder.mid_block.attentions.0.value.weight", "vae.decoder.mid_block.attentions.0.value.bias", "vae.decoder.mid_block.attentions.0.proj_attn.weight", "vae.decoder.mid_block.attentions.0.proj_attn.bias".

**Comment by haixiao-stack** [comment]
Did you solve it? I meet the same issue

**Comment by Ubinya** [comment]
Same problem for depth model

**Comment by Ubinya** [comment]
Solved by aligning the diffusers and transformers version precisely with the requirements.

**Comment by HariWu1995** [comment]
Or if you want to use different `diffusers`, you can overwrite the `state dict` with this function:

`def rename_attention_keys(state_dict):

      rename_map = {
              'query': 'to_q',
                'key': 'to_k',
              'value': 'to_v',
          'proj_attn': 'to_out.0',
      }
  
      new_state_dict = {}
      for k, v in state_dict.items():
          # Skip keys not related to attention remapping
          if 'attentions.0' in k:
              replaced = False
              for old, new in rename_map.items():
                  if f".{old}." in k:
                      new_key = k.replace(f".{old}.", f".{new}.")
                      new_state_dict[new_key] = v
                      replaced = True
                      break
              if not replaced:
                  new_state_dict[k] = v
          else:
              new_state_dict[k] = v
      return new_state_dict`
